
# Now let's begin with data_ingestion configuration

# creating the root folder as artifacts

artifacts_root : artifacts

# defining the data_ingestion coonfiguration

data_ingestion:
  # then again creating data_ingestion folder inside the artifacts
  root_dir: artifacts/data_ingestion
